In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('loan_data_1.csv')

In [3]:
df.describe()

,Unnamed: 0,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,381.000000,369.000000,363.000000,373.000000,370.000000,351.000000
mean,190.000000,3563.422764,1267.005289,104.914209,340.864865,0.837607
std,110.129469,1427.371257,2388.048316,28.484822,68.549257,0.369338
min,0.000000,150.000000,0.000000,9.000000,12.000000,0.000000
25%,95.000000,2583.000000,0.000000,90.000000,360.000000,1.000000
50%,190.000000,3326.000000,830.000000,110.000000,360.000000,1.000000
75%,285.000000,4226.000000,2008.000000,127.000000,360.000000,1.000000
max,380.000000,9703.000000,33837.000000,150.000000,480.000000,1.000000

In [4]:
df.shape

(381, 14)

In [5]:
df.head()

,Unnamed: 0,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,LP001003,Male,Yes,1,Graduate,No,4583.0,1508.0,128.0,360.0,1.0,Rural,N
1,1,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.0,1.0,Urban,Y
2,2,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.0,1.0,Urban,Y
3,3,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.0,1.0,Urban,Y
4,4,LP001013,Male,Yes,0,Not Graduate,No,2333.0,1516.0,95.0,360.0,1.0,Urban,Y

In [6]:
df.tail()

,Unnamed: 0,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
376,376,LP002953,Male,Yes,3+,Graduate,No,5703.0,0.0,128.0,360.0,1.0,Urban,Y
377,377,LP002974,Male,Yes,0,Graduate,No,3232.0,NaN,108.0,360.0,1.0,Rural,Y
378,378,LP002978,Female,No,0,Graduate,No,2900.0,0.0,71.0,360.0,1.0,Rural,Y
379,379,LP002979,Male,Yes,3+,Graduate,No,4106.0,0.0,40.0,180.0,1.0,Rural,Y
380,380,LP002990,Female,No,0,NaN,Yes,4583.0,0.0,133.0,360.0,0.0,Semiurban,N

In [7]:
df.isnull().sum()

Unnamed: 0            0
Loan_ID               0
Gender                5
Married               0
Dependents            8
Education             6
Self_Employed        21
ApplicantIncome      12
CoapplicantIncome    18
LoanAmount            8
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         381 non-null    int64
 1   Loan_ID            381 non-null    str
 2   Gender             376 non-null    str
 3   Married            381 non-null    str
 4   Dependents         373 non-null    str
 5   Education          375 non-null    str
 6   Self_Employed      360 non-null    str
 7   ApplicantIncome    369 non-null    float64
 8   CoapplicantIncome  363 non-null    float64
 9   LoanAmount         373 non-null    float64
 10  Loan_Amount_Term   370 non-null    float64
 11  Credit_History     351 non-null    float64
 12  Property_Area      381 non-null    str
 13  Loan_Status        381 non-null    str
dtypes: float64(5), int64(1), str(8)
memory usage: 41.8 KB

In [10]:
df.shape

(381, 14)

In [11]:
df["Gender"].value_counts()

Gender
Male      291
Female     85
Name: count, dtype: int64

In [12]:
df["Dependents"].value_counts()

Dependents
0     234
2      59
1      52
3+     28
Name: count, dtype: int64

In [13]:
df["Education"].value_counts()

Education
Graduate        274
Not Graduate    101
Name: count, dtype: int64

In [14]:
df["Self_Employed"].value_counts()

Self_Employed
No     325
Yes     35
Name: count, dtype: int64

In [15]:
df["Married"].value_counts()

Married
Yes    228
No     153
Name: count, dtype: int64

In [16]:
df["Credit_History"].value_counts()

Credit_History
1.0    294
0.0     57
Name: count, dtype: int64

In [17]:
df[["ApplicantIncome", "CoapplicantIncome", "LoanAmount", "Loan_Amount_Term"]].describe()

       ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term
count       369.000000         363.000000  373.000000        370.000000
mean       3563.422764        1267.005289  104.914209        340.864865
std        1427.371257        2388.048316   28.484822         68.549257
min         150.000000           0.000000    9.000000         12.000000
25%        2583.000000           0.000000   90.000000        360.000000
50%        3326.000000         830.000000  110.000000        360.000000
75%        4226.000000        2008.000000  127.000000        360.000000
max        9703.000000       33837.000000  150.000000        480.000000

In [18]:
df["Loan_Status"].value_counts()

Loan_Status
Y    271
N    110
Name: count, dtype: int64

In [19]:
df["Loan_Status"].value_counts(normalize=True)

Loan_Status
Y    0.711286
N    0.288714
Name: proportion, dtype: float64

In [20]:
pd.crosstab(df["Credit_History"], df["Loan_Status"])

Loan_Status      N    Y
Credit_History
0.0             54    3
1.0             52  242

In [21]:
pd.crosstab(
    df["Credit_History"],
    df["Loan_Status"],
    normalize="index"
)

Loan_Status            N         Y
Credit_History
0.0             0.947368  0.052632
1.0             0.176871  0.823129

In [22]:
df["Credit_History"].fillna(0)

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
376    1.0
377    1.0
378    1.0
379    1.0
380    0.0
Name: Credit_History, Length: 381, dtype: float64

In [23]:
pd.crosstab(
    df["Education"],
    df["Loan_Status"],
    normalize="index"
)

Loan_Status          N         Y
Education
Graduate      0.266423  0.733577
Not Graduate  0.316832  0.683168

In [24]:
df.groupby("Loan_Status")["ApplicantIncome"].median()

Loan_Status
N    3409.0
Y    3273.0
Name: ApplicantIncome, dtype: float64

In [25]:
df.groupby("Loan_Status")["LoanAmount"].median()

Loan_Status
N    106.0
Y    111.5
Name: LoanAmount, dtype: float64

In [26]:
pd.crosstab(
    df["Property_Area"],
    df["Loan_Status"],
    normalize="index"
)

Loan_Status           N         Y
Property_Area
Rural          0.386792  0.613208
Semiurban      0.201342  0.798658
Urban          0.309524  0.690476

In [27]:
df = df.drop(["Unnamed: 0", "Loan_ID"], axis=1)

In [28]:
X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

In [29]:
X.shape

(381, 11)

In [30]:
y.shape

(381,)

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [32]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(304, 11)
(77, 11)
(304,)
(77,)

In [33]:
categorical_features = [
    "Gender",
    "Married",
    "Dependents",
    "Education",
    "Self_Employed",
    "Property_Area"
]

numerical_features = [
    "ApplicantIncome",
    "CoapplicantIncome",
    "LoanAmount",
    "Loan_Amount_Term",
    "Credit_History"
]

In [34]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [35]:

numerical_transformer = SimpleImputer(strategy="median")

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [36]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [37]:
model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

In [38]:
model.fit(X_train, y_train)

c:\Users\HP\Downloads\Python Tutorial\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  SimpleImputer(strategy='median'),
                                                  ['ApplicantIncome',
                                                   'CoapplicantIncome',
                                                   'LoanAmount',
                                                   'Loan_Amount_Term',
                                                   'Credit_History']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Gender', 'Married',
                                                   'Dependents', 'Education',
                                                   'Self_Employed',
                                                   'Property_Area'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [39]:
y_pred = model.predict(X_test)

In [40]:
print(y_pred)

['Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y']

In [41]:
print(y_test.values)

<StringArray>
['Y', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y', 'Y',
 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y',
 'Y', 'Y']
Length: 77, dtype: str

In [42]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8571428571428571

In [43]:
print("Accuracy:", accuracy * 100, "%")

Accuracy: 85.71428571428571 %

In [44]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[11 11]
 [ 0 55]]

In [45]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           N       1.00      0.50      0.67        22
           Y       0.83      1.00      0.91        55

    accuracy                           0.86        77
   macro avg       0.92      0.75      0.79        77
weighted avg       0.88      0.86      0.84        77

In [46]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline

tree_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", DecisionTreeClassifier(random_state=42))
])

tree_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  SimpleImputer(strategy='median'),
                                                  ['ApplicantIncome',
                                                   'CoapplicantIncome',
                                                   'LoanAmount',
                                                   'Loan_Amount_Term',
                                                   'Credit_History']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Gender', 'Married',
                                                   'Dependents', 'Education',
                                                   'Self_Employed',
                                                   'Property_Area'])])),
                ('classifier', DecisionTreeClassifier(random_state=42))])

In [47]:
y_pred_tree = tree_model.predict(X_test)

print(y_pred_tree)

['Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'N' 'N' 'Y'
 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N'
 'Y' 'Y' 'Y' 'N' 'Y']

In [48]:
from sklearn.metrics import accuracy_score

tree_accuracy = accuracy_score(y_test, y_pred_tree)

print("Decision Tree Accuracy:", tree_accuracy)
print("Decision Tree Accuracy:", tree_accuracy * 100, "%")

Decision Tree Accuracy: 0.7402597402597403
Decision Tree Accuracy: 74.02597402597402 %

In [49]:
from sklearn.metrics import confusion_matrix

cm_tree = confusion_matrix(y_test, y_pred_tree)

print(cm_tree)

[[13  9]
 [11 44]]

In [50]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_tree))

              precision    recall  f1-score   support

           N       0.54      0.59      0.57        22
           Y       0.83      0.80      0.81        55

    accuracy                           0.74        77
   macro avg       0.69      0.70      0.69        77
weighted avg       0.75      0.74      0.74        77

In [51]:
from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ))
])

In [52]:
rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  SimpleImputer(strategy='median'),
                                                  ['ApplicantIncome',
                                                   'CoapplicantIncome',
                                                   'LoanAmount',
                                                   'Loan_Amount_Term',
                                                   'Credit_History']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Gender', 'Married',
                                                   'Dependents', 'Education',
                                                   'Self_Employed',
                                                   'Property_Area'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [53]:
y_pred_rf = rf_model.predict(X_test)

print(y_pred_rf)

['Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y'
 'Y' 'N' 'Y' 'Y' 'Y']

In [54]:
from sklearn.metrics import accuracy_score

rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", rf_accuracy)
print("Random Forest Accuracy:", rf_accuracy * 100, "%")

Random Forest Accuracy: 0.8831168831168831
Random Forest Accuracy: 88.31168831168831 %

In [55]:
from sklearn.metrics import confusion_matrix

cm_rf = confusion_matrix(y_test, y_pred_rf)

print(cm_rf)

[[13  9]
 [ 0 55]]

In [56]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           N       1.00      0.59      0.74        22
           Y       0.86      1.00      0.92        55

    accuracy                           0.88        77
   macro avg       0.93      0.80      0.83        77
weighted avg       0.90      0.88      0.87        77

In [57]:
from sklearn.model_selection import cross_val_score

rf_cv_scores = cross_val_score(
    rf_model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("CV Scores:", rf_cv_scores)
print("Mean CV Accuracy:", rf_cv_scores.mean())

CV Scores: [0.83116883 0.78947368 0.84210526 0.81578947 0.80263158]
Mean CV Accuracy: 0.8162337662337663

In [58]:
lr_cv_scores = cross_val_score(
    model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("Logistic Regression CV Scores:", lr_cv_scores)
print("Mean CV Accuracy:", lr_cv_scores.mean())

c:\Users\HP\Downloads\Python Tutorial\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\HP\Downloads\Python Tutorial\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\HP\Downloads\Python Tutorial\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\HP\Downloads\Python Tutorial\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression CV Scores: [0.84415584 0.77631579 0.81578947 0.89473684 0.86842105]
Mean CV Accuracy: 0.8398838004101161

c:\Users\HP\Downloads\Python Tutorial\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [59]:
tree_cv_scores = cross_val_score(
    tree_model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("Decision Tree CV Scores:", tree_cv_scores)
print("Mean CV Accuracy:", tree_cv_scores.mean())

Decision Tree CV Scores: [0.80519481 0.80263158 0.73684211 0.75       0.78947368]
Mean CV Accuracy: 0.7768284347231716

In [61]:
from sklearn.preprocessing import StandardScaler

numerical_transformer_scaled = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_scaled = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer_scaled, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [62]:
scaled_lr_model = Pipeline(steps=[
    ("preprocessor", preprocessor_scaled),
    ("classifier", LogisticRegression(max_iter=1000))
])

In [63]:
scaled_lr_cv_scores = cross_val_score(
    scaled_lr_model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("Scaled Logistic Regression CV Scores:", scaled_lr_cv_scores)
print("Mean CV Accuracy:", scaled_lr_cv_scores.mean())

Scaled Logistic Regression CV Scores: [0.84415584 0.77631579 0.81578947 0.89473684 0.86842105]
Mean CV Accuracy: 0.8398838004101161

In [64]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Train the scaled Logistic Regression
scaled_lr_model.fit(X_train, y_train)

# Predictions
y_pred_scaled_lr = scaled_lr_model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred_scaled_lr))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_scaled_lr))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_scaled_lr))

Accuracy: 0.8571428571428571

Confusion Matrix:
[[11 11]
 [ 0 55]]

Classification Report:
              precision    recall  f1-score   support

           N       1.00      0.50      0.67        22
           Y       0.83      1.00      0.91        55

    accuracy                           0.86        77
   macro avg       0.92      0.75      0.79        77
weighted avg       0.88      0.86      0.84        77

In [65]:
feature_names = scaled_lr_model.named_steps["preprocessor"].get_feature_names_out()

coefficients = scaled_lr_model.named_steps["classifier"].coef_[0]

feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coefficients
})

feature_importance["Absolute_Coefficient"] = (
    feature_importance["Coefficient"].abs()
)

feature_importance = feature_importance.sort_values(
    "Absolute_Coefficient",
    ascending=False
)

feature_importance

                         Feature  Coefficient  Absolute_Coefficient
4            num__Credit_History     1.568609              1.568609
18  cat__Property_Area_Semiurban     0.505720              0.505720
2                num__LoanAmount     0.397288              0.397288
17      cat__Property_Area_Rural    -0.382362              0.382362
7                cat__Married_No    -0.233757              0.233757
8               cat__Married_Yes     0.233404              0.233404
10             cat__Dependents_1    -0.198707              0.198707
0           num__ApplicantIncome    -0.182471              0.182471
14   cat__Education_Not Graduate    -0.174277              0.174277
13       cat__Education_Graduate     0.173924              0.173924
9              cat__Dependents_0     0.162933              0.162933
16        cat__Self_Employed_Yes    -0.157032              0.157032
15         cat__Self_Employed_No     0.156679              0.156679
11             cat__Dependents_2     0.155046              0.155046
19      cat__Property_Area_Urban    -0.123711              0.123711
12            cat__Dependents_3+    -0.119625              0.119625
1         num__CoapplicantIncome    -0.119141              0.119141
3          num__Loan_Amount_Term    -0.118866              0.118866
5             cat__Gender_Female    -0.062405              0.062405
6               cat__Gender_Male     0.062052              0.062052

In [66]:
y_prob = scaled_lr_model.predict_proba(X_test)

print(y_prob[:10])

[[0.11136457 0.88863543]
 [0.91899154 0.08100846]
 [0.0562781  0.9437219 ]
 [0.08827134 0.91172866]
 [0.17553285 0.82446715]
 [0.97132645 0.02867355]
 [0.17244813 0.82755187]
 [0.07356405 0.92643595]
 [0.96754059 0.03245941]
 [0.25475148 0.74524852]]

In [67]:
y_prob_approved = scaled_lr_model.predict_proba(X_test)[:, 1]

for threshold in [0.3, 0.4, 0.5, 0.6, 0.7]:
    y_pred_threshold = np.where(
        y_prob_approved >= threshold,
        "Y",
        "N"
    )

    cm = confusion_matrix(y_test, y_pred_threshold)

    print("Threshold:", threshold)
    print(cm)
    print()

Threshold: 0.3
[[11 11]
 [ 0 55]]

Threshold: 0.4
[[11 11]
 [ 0 55]]

Threshold: 0.5
[[11 11]
 [ 0 55]]

Threshold: 0.6
[[11 11]
 [ 0 55]]

Threshold: 0.7
[[12 10]
 [ 2 53]]

In [68]:
y_prob_approved = scaled_lr_model.predict_proba(X_test)[:, 1]

for threshold in [0.3, 0.4, 0.5, 0.6, 0.7]:
    y_pred_threshold = np.where(
        y_prob_approved >= threshold,
        "Y",
        "N"
    )

    cm = confusion_matrix(y_test, y_pred_threshold)

    print("Threshold:", threshold)
    print(cm)
    print()

Threshold: 0.3
[[11 11]
 [ 0 55]]

Threshold: 0.4
[[11 11]
 [ 0 55]]

Threshold: 0.5
[[11 11]
 [ 0 55]]

Threshold: 0.6
[[11 11]
 [ 0 55]]

Threshold: 0.7
[[12 10]
 [ 2 53]]

In [69]:
import numpy as np

In [70]:
print("Minimum P(Y):", y_prob_approved.min())
print("Maximum P(Y):", y_prob_approved.max())

print("\nProbabilities sorted:")
print(np.sort(y_prob_approved))

Minimum P(Y): 0.027056153274851252
Maximum P(Y): 0.9532845163692871

Probabilities sorted:
[0.02705615 0.02867355 0.03245941 0.05236681 0.05365996 0.05513435
 0.05695834 0.06990886 0.06993621 0.08100846 0.12196888 0.66002309
 0.67596321 0.69566016 0.71281163 0.71425406 0.71778894 0.71952879
 0.73473997 0.74524852 0.75378418 0.76128683 0.76656441 0.76849309
 0.77011994 0.77273392 0.77806629 0.79776587 0.80341425 0.80594004
 0.80974021 0.81092409 0.81429033 0.81567194 0.81581618 0.81692837
 0.82446715 0.82755187 0.8350446  0.84270357 0.84574696 0.84858672
 0.85259565 0.85480024 0.85557111 0.85778991 0.85838323 0.86340161
 0.87147411 0.8721771  0.87488613 0.88438104 0.8862727  0.88636093
 0.88846721 0.88863543 0.90256434 0.90544282 0.9080605  0.91097498
 0.91172866 0.9120209  0.91203511 0.91633407 0.92269667 0.92330716
 0.92643595 0.92861657 0.92966034 0.93068483 0.93135973 0.94158739
 0.9437219  0.94515578 0.94735648 0.94919957 0.95328452]

In [71]:
from sklearn.model_selection import cross_validate

models = {
    "Logistic Regression": scaled_lr_model,
    "Decision Tree": tree_model,
    "Random Forest": rf_model
}

for name, model in models.items():

    scores = cross_validate(
        model,
        X,
        y,
        cv=5,
        scoring=["accuracy", "precision_macro", "recall_macro", "f1_macro"]
    )

    print("\n", name)
    print("Accuracy :", scores["test_accuracy"].mean())
    print("Precision:", scores["test_precision_macro"].mean())
    print("Recall   :", scores["test_recall_macro"].mean())
    print("F1 Score :", scores["test_f1_macro"].mean())

 Logistic Regression
Accuracy : 0.8398838004101161
Precision: 0.8700397270639808
Recall   : 0.7361952861952862
F1 Score : 0.7654898855430318

 Decision Tree
Accuracy : 0.7768284347231716
Precision: 0.736789745600334
Recall   : 0.7323569023569024
F1 Score : 0.7282665267210918

 Random Forest
Accuracy : 0.8162337662337663
Precision: 0.8112143317368726
Recall   : 0.7249831649831648
F1 Score : 0.7447706670208729

In [72]:
final_model = scaled_lr_model

final_model.fit(X_train, y_train)

print("Final model trained successfully!")

Final model trained successfully!

In [73]:
final_predictions = final_model.predict(X_test)

print("Final Test Accuracy:",
      accuracy_score(y_test, final_predictions))

print("\nFinal Confusion Matrix:")
print(confusion_matrix(y_test, final_predictions))

print("\nFinal Classification Report:")
print(classification_report(y_test, final_predictions))

Final Test Accuracy: 0.8571428571428571

Final Confusion Matrix:
[[11 11]
 [ 0 55]]

Final Classification Report:
              precision    recall  f1-score   support

           N       1.00      0.50      0.67        22
           Y       0.83      1.00      0.91        55

    accuracy                           0.86        77
   macro avg       0.92      0.75      0.79        77
weighted avg       0.88      0.86      0.84        77

In [74]:
import joblib

joblib.dump(final_model, "loan_approval_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [75]:
import joblib

loaded_model = joblib.load("loan_approval_model.pkl")

print("Model loaded successfully!")

Model loaded successfully!

In [76]:
import pandas as pd

new_applicant = pd.DataFrame([{
    "Gender": "Male",
    "Married": "Yes",
    "Dependents": "1",
    "Education": "Graduate",
    "Self_Employed": "No",
    "ApplicantIncome": 5000,
    "CoapplicantIncome": 1500,
    "LoanAmount": 120,
    "Loan_Amount_Term": 360,
    "Credit_History": 1.0,
    "Property_Area": "Semiurban"
}])

print(new_applicant)

  Gender Married Dependents Education Self_Employed  ApplicantIncome  \
0   Male     Yes          1  Graduate            No             5000

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0               1500         120               360             1.0

  Property_Area
0     Semiurban

In [77]:
prediction = loaded_model.predict(new_applicant)

print("Loan Prediction:", prediction[0])

Loan Prediction: Y

In [78]:
probability = loaded_model.predict_proba(new_applicant)

print("Probability of Loan Rejection (N):", probability[0][0])
print("Probability of Loan Approval (Y):", probability[0][1])

Probability of Loan Rejection (N): 0.10178630878249484
Probability of Loan Approval (Y): 0.8982136912175052

In [79]:
def predict_loan(
    Gender,
    Married,
    Dependents,
    Education,
    Self_Employed,
    ApplicantIncome,
    CoapplicantIncome,
    LoanAmount,
    Loan_Amount_Term,
    Credit_History,
    Property_Area
):
        new_applicant = pd.DataFrame([{
        "Gender": Gender,
        "Married": Married,
        "Dependents": Dependents,
        "Education": Education,
        "Self_Employed": Self_Employed,
        "ApplicantIncome": ApplicantIncome,
        "CoapplicantIncome": CoapplicantIncome,
        "LoanAmount": LoanAmount,
        "Loan_Amount_Term": Loan_Amount_Term,
        "Credit_History": Credit_History,
        "Property_Area": Property_Area
    }])

        prediction = loaded_model.predict(new_applicant)[0]

        probability = loaded_model.predict_proba(new_applicant)[0]

        return prediction, probability

In [80]:
prediction, probability = predict_loan(
    "Male",
    "Yes",
    "1",
    "Graduate",
    "No",
    5000,
    1500,
    120,
    360,
    1.0,
    "Semiurban"
)

print("Loan Prediction:", prediction)
print("Probability of Rejection (N):", probability[0])
print("Probability of Approval (Y):", probability[1])

Loan Prediction: Y
Probability of Rejection (N): 0.10178630878249484
Probability of Approval (Y): 0.8982136912175052